export const ROUTES = {
  LANDING: "/",
  LOGIN: "/login",
  VERIFY: "/verify",
  ONBOARDING: {
    ROOT: "/onboarding",
    PHOTOS: "/onboarding/photos",
    OCCUPATION: "/onboarding/occupation",
    MBTI: "/onboarding/mbti",
    HOBBIES: "/onboarding/hobbies",
    PERSONALITY: "/onboarding/personality",
    IDEAL_TYPE: "/onboarding/ideal-type",
    AREA: "/onboarding/area",
    PREFERENCES: "/onboarding/preferences",
    COMPLETE: "/onboarding/complete",
  },
  HOME: "/home",
  QUESTIONS: "/questions",
  MATCHES: "/matches",
  CHAT: (id: number) => `/matches/${id}/chat` as const,
  MISSIONS: "/missions",
  MISSION_DETAIL: (id: number) => `/missions/${id}` as const,
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  AUTH_CALLBACK: "/api/auth/callback",
  ADMIN: {
    ROOT: "/admin",
    REPORTS: "/admin/reports",
    USERS: "/admin/users",
    NO_SHOWS: "/admin/no-shows",
  },
} as const;
